### ISSUE TITLE
PubsubLiteIO Message Type Inconsistencies

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite#608]
The message types used by [`PubsubLiteIO`](https://googleapis.dev/java/google-cloud-pubsublite/latest/com/google/cloud/pubsublite/beam/PubsubLiteIO.html) is not ideal. 

Reading from Lite currently returns a `SequencedMessage`, and writing to Lite requires a `PubSubMessage`. This can be very confusing for users because [`PubsubIO`](https://beam.apache.org/releases/javadoc/2.28.0/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.html) expects a `PubsubMessage` for reading and writing. Notice the lower cased 's' here! 😣

Ideally a standard message type is shared between the two I/O connectors. Additionally, Lite shall consider providing other ways to read messages as well, for examples, `readStrings`, `readProtos`, `readMessages`, which are all available for `PubsubIO`.

**Comment by manuelmenzella-google** [comment]
I would like for us to carefully consider the tradeoffs when making this change.

If I understand correctly, this Issue proposes making the Pub/Sub Lite IO return CPS messages instead of the Lite-specific ones. This would be equivalent to what we've done in the Beam client libraries; for example, the MessageReceiver returns a [transformed](https://github.com/googleapis/java-pubsublite/blob/343afbffc2be92cb6be2670ef3ec34c599cd95dc/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/MessageTransformer.java) Pub/Sub Lite message into a CPS message.

Unfortunately, this limits Pub/Sub Lite's flexibility when it comes to exposing attributes that only apply to Pub/Sub Lite and not Cloud Pub/Sub. Alternatively, this also limits Cloud Pub/Sub's ability to extend the API for features that Lite does not support. An example of the former is the awkward parsing of Cloud Pub/Sub's messages' IDs to extract the partition/offsets; e.g. [MessageMetadata](https://github.com/googleapis/java-pubsublite/blob/343afbffc2be92cb6be2670ef3ec34c599cd95dc/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/MessageMetadata.java).

What do you think, Tianzi? Is the overall result better if we make this change?

**Comment by dpcollins-google** [comment]
> Reading from Lite currently returns a SequencedMessage, and writing to Lite requires a PubSubMessage. This can be very confusing for users because PubsubIO expects a PubsubMessage for reading and writing

The PubsubMessage used in Beam is also a different PubsubMessage than the proto, and includes only a subset of the fields. There's nothing that can be done with the `key` field for example, since the beam version doesn't support ordering_key.

> Ideally a standard message type is shared between the two I/O connectors.

This does limit flexibility, there are some messages which are unrepresentable in the Cloud Pub/Sub message, expecially given the ordering key limitations.

What I would like (and originally had until the beam reviewer told me to remove it) is a simple PTransform method to convert from PubsubLite SequencedMessages to the CPS Beam PubsubMessages, failing if any are non-convertible. I can add this back.

> Additionally, Lite shall consider providing other ways to read messages as well, for examples, readStrings, readProtos, readMessages, which are all available for PubsubIO.

I very much disagree with this. None of these methods belong in PubsubIO, and I would like to remove them. It is trivial in beam to add a method deserializing the payload of messages using MapElements. This serialization code should not be the responsibility of the I/O module.

**Comment by anguillanneuf** [comment]
I think we can work around Lite needs to have its own message type by providing a `readString` and `writeString` method. This will at least help make Lite work with Pub/Sub. [`PubsubIO`](https://beam.apache.org/releases/javadoc/2.28.0/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.html) does provide these methods.

I believe PubsubIO is using an older version of Pub/Sub, which may explain why the ordering key field is unavailable. I know for Python, the Pub/Sub version with Beam is still at 1.y.z although we are at 2.4.z now.

Can Lite support the same message type for reading and writing within itself then?

**Comment by dpcollins-google** [comment]
> I think we can work around Lite needs to have its own message type by providing a readString and writeString method.

I don't think these methods should be provided. The user can easily implement this by `MapElements.into(TypeDescriptor.of(String.class)).via(message -> message.message().payload().toStringUtf8());`. Throwing away all of the attributes is not expected to be a common enough case to warrant building this in.

> which may explain why the ordering key field is unavailable

No. Pub/Sub IO uses a bespoke type from the proto message. This is implemented here https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubMessage.java and is only converted to the wire message deep in the guts of the Dataflow-Beam interop layer (I forget where). Its quite hard to wire through all the layers to add this field, its not just a version bump.

> Can Lite support the same message type for reading and writing within itself then?

No. Pub/Sub is wrong here, because Pub/Sub on a service level uses the same message proto type but doesn't allow certain fields to be set on publish. Fields like publish_timestamp and cursor are intentionally only available on the SequencedMessage not the PubSubMessage (which is entirely user provided).

**Comment by manuelmenzella-google** [comment]
> I very much disagree with this. None of these methods belong in PubsubIO, and I would like to remove them. It is trivial in beam to add a method deserializing the payload of messages using MapElements. This serialization code should not be the responsibility of the I/O module.

This seems to overemphasize orthogonality over pragmatism. Is it really that bad to provide this helper method if it satisfies a common use case? If these methods are popular, I don't see a significant downside to including them.

Additionally, following this line of reasoning, couldn't you argue that the transform from Lite's SequencedMessage to CPS's PubsubMessage also doesn't belong in Lite's IO? After all, clients can perform the exact same transformation themselves. But still, we both agree that this is a useful tool to provide.

**Comment by anguillanneuf** [comment]
Working with Strings is extremely common in ETL workflows (doing grouping, counting, aggregating), and having a readString and writeString method is just more convenient than asking the user to add a PTransform step. 
Even in Pub/Sub Lite, our code samples all work with `com.google.pubsub.v1.PubsubMessage`. Why should Pub/Sub Lite confuse them some more?

**Comment by manuelmenzella-google** [comment]
> Even in Pub/Sub Lite, our code samples all work with com.google.pubsub.v1.PubsubMessage. Why should Pub/Sub Lite confuse them some more?

CPS's PubsubMessage does have significant drawbacks, as Dan pointed out, so I would like to avoid making this the default message returned by Lite's IO. I like his proposal of the transform. Do you think this would satisfy your concern, Tianzi?

**Comment by anguillanneuf** [comment]
Yep, the option to transform Lite messages to Beam's `PubsubMessage` will be nice.
We can have a default read(), a readMessages(), and a readStrings() and the same for write.

**Comment by manuelmenzella-google** [comment]
What would be the difference between `read()` and `readMessages()`?

**Comment by anguillanneuf** [comment]
`read()` would return `SequencedMessage` used by Lite. But `readMessages()` returns `PubsubMessage` used by both Pub/Sub and Pub/Sub Lite.

**Comment by dpcollins-google** [comment]
My concern with this as proposed would be it is not entirely clear with from the name what the methods do. I don't think the following would be a huge increase in verbosity, but makes it more explicit:

```
public static PTransform<PCollection<SequencedMessage>, PCollection<PubsubMessage>> toCpsMessages();
```

Used like:

```
PCollection<PubsubMessage> cpsMessages = PubsubLiteIO.read(options).apply(CloudPubsubTransforms.toCpsMessages());
```

**Comment by manuelmenzella-google** [comment]
> `read()` would return `SequencedMessage` used by Lite. But `readMessages()` returns `PubsubMessage` used by both Pub/Sub and Pub/Sub Lite.

Ah. Hmm, that does feel like making PubsubMessage the default. It's not clear what the customer is requesting in each method.

What I was expecting is more in line with Dan's suggestion, where the conversion is explicit. WDYT?

**Comment by anguillanneuf** [comment]
Ok, just one nit `toCpsMessages()` is better changed to `toPubsubMessage()`.

**Comment by dpcollins-google** [comment]
Sure. I'm not picky on the naming, so much as inclusion

**Comment by dpcollins-google** [comment]
This is resolved by adding the PubsubMessageTransfroms class which has the compatability transform on the read side.
